# Generated by Django 3.1.5 on 2021-03-31 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210124_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-id']},
        ),
    ]
